/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as WellnessRouteImport } from './routes/wellness'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ClassesIndexRouteImport } from './routes/classes.index'
import { Route as ClassesClassIdRouteImport } from './routes/classes.$classId'
import { Route as GameJoinRouteImport } from './routes/game.join'
import { Route as QuizzesQuizIdRouteImport } from './routes/quizzes.$quizId'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsSessionIdRouteImport } from './routes/reports.$sessionId'
import { Route as AdminContentIndexRouteImport } from './routes/admin.content.index'
import { Route as AdminContentQuizIdRouteImport } from './routes/admin.content.$quizId'
import { Route as AdminContentGenerateRouteImport } from './routes/admin.content.generate'
import { Route as AdminContentNewRouteImport } from './routes/admin.content.new'
import { Route as ClassesClassIdIndexRouteImport } from './routes/classes.$classId.index'
import { Route as GameHostSessionIdRouteImport } from './routes/game.host.$sessionId'
import { Route as GamePlaySessionIdRouteImport } from './routes/game.play.$sessionId'
import { Route as ClassesClassIdQuizzesQuizIdRouteImport } from './routes/classes.$classId.quizzes.$quizId'
import { Route as ClassesClassIdQuizzesGenerateRouteImport } from './routes/classes.$classId.quizzes.generate'
import { Route as ClassesClassIdQuizzesNewRouteImport } from './routes/classes.$classId.quizzes.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const WellnessRoute = WellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesIndexRoute = ClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesClassIdRoute = ClassesClassIdRouteImport.update({
  id: '/classes/$classId',
  path: '/classes/$classId',
  getParentRoute: () => rootRouteImport,
} as any)
const GameJoinRoute = GameJoinRouteImport.update({
  id: '/game/join',
  path: '/game/join',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesQuizIdRoute = QuizzesQuizIdRouteImport.update({
  id: '/quizzes/$quizId',
  path: '/quizzes/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSessionIdRoute = ReportsSessionIdRouteImport.update({
  id: '/reports/$sessionId',
  path: '/reports/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentIndexRoute = AdminContentIndexRouteImport.update({
  id: '/admin/content/',
  path: '/admin/content/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentQuizIdRoute = AdminContentQuizIdRouteImport.update({
  id: '/admin/content/$quizId',
  path: '/admin/content/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentGenerateRoute = AdminContentGenerateRouteImport.update({
  id: '/admin/content/generate',
  path: '/admin/content/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentNewRoute = AdminContentNewRouteImport.update({
  id: '/admin/content/new',
  path: '/admin/content/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesClassIdIndexRoute = ClassesClassIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClassesClassIdRoute,
} as any)
const GameHostSessionIdRoute = GameHostSessionIdRouteImport.update({
  id: '/game/host/$sessionId',
  path: '/game/host/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamePlaySessionIdRoute = GamePlaySessionIdRouteImport.update({
  id: '/game/play/$sessionId',
  path: '/game/play/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesClassIdQuizzesQuizIdRoute =
  ClassesClassIdQuizzesQuizIdRouteImport.update({
    id: '/quizzes/$quizId',
    path: '/quizzes/$quizId',
    getParentRoute: () => ClassesClassIdRoute,
  } as any)
const ClassesClassIdQuizzesGenerateRoute =
  ClassesClassIdQuizzesGenerateRouteImport.update({
    id: '/quizzes/generate',
    path: '/quizzes/generate',
    getParentRoute: () => ClassesClassIdRoute,
  } as any)
const ClassesClassIdQuizzesNewRoute =
  ClassesClassIdQuizzesNewRouteImport.update({
    id: '/quizzes/new',
    path: '/quizzes/new',
    getParentRoute: () => ClassesClassIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/dashboard': typeof DashboardRoute
  '/focus': typeof FocusRoute
  '/journey': typeof JourneyRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/wellness': typeof WellnessRoute
  '/classes/$classId': typeof ClassesClassIdRouteWithChildren
  '/game/join': typeof GameJoinRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdRoute
  '/reports/$sessionId': typeof ReportsSessionIdRoute
  '/admin/': typeof AdminIndexRoute
  '/classes/': typeof ClassesIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/admin/content/$quizId': typeof AdminContentQuizIdRoute
  '/admin/content/generate': typeof AdminContentGenerateRoute
  '/admin/content/new': typeof AdminContentNewRoute
  '/game/host/$sessionId': typeof GameHostSessionIdRoute
  '/game/play/$sessionId': typeof GamePlaySessionIdRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/classes/$classId/': typeof ClassesClassIdIndexRoute
  '/classes/$classId/quizzes/$quizId': typeof ClassesClassIdQuizzesQuizIdRoute
  '/classes/$classId/quizzes/generate': typeof ClassesClassIdQuizzesGenerateRoute
  '/classes/$classId/quizzes/new': typeof ClassesClassIdQuizzesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/dashboard': typeof DashboardRoute
  '/focus': typeof FocusRoute
  '/journey': typeof JourneyRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/wellness': typeof WellnessRoute
  '/game/join': typeof GameJoinRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdRoute
  '/reports/$sessionId': typeof ReportsSessionIdRoute
  '/admin': typeof AdminIndexRoute
  '/classes': typeof ClassesIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/admin/content/$quizId': typeof AdminContentQuizIdRoute
  '/admin/content/generate': typeof AdminContentGenerateRoute
  '/admin/content/new': typeof AdminContentNewRoute
  '/game/host/$sessionId': typeof GameHostSessionIdRoute
  '/game/play/$sessionId': typeof GamePlaySessionIdRoute
  '/admin/content': typeof AdminContentIndexRoute
  '/classes/$classId': typeof ClassesClassIdIndexRoute
  '/classes/$classId/quizzes/$quizId': typeof ClassesClassIdQuizzesQuizIdRoute
  '/classes/$classId/quizzes/generate': typeof ClassesClassIdQuizzesGenerateRoute
  '/classes/$classId/quizzes/new': typeof ClassesClassIdQuizzesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/dashboard': typeof DashboardRoute
  '/focus': typeof FocusRoute
  '/journey': typeof JourneyRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/wellness': typeof WellnessRoute
  '/classes/$classId': typeof ClassesClassIdRouteWithChildren
  '/game/join': typeof GameJoinRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdRoute
  '/reports/$sessionId': typeof ReportsSessionIdRoute
  '/admin/': typeof AdminIndexRoute
  '/classes/': typeof ClassesIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/admin/content/$quizId': typeof AdminContentQuizIdRoute
  '/admin/content/generate': typeof AdminContentGenerateRoute
  '/admin/content/new': typeof AdminContentNewRoute
  '/game/host/$sessionId': typeof GameHostSessionIdRoute
  '/game/play/$sessionId': typeof GamePlaySessionIdRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/classes/$classId/': typeof ClassesClassIdIndexRoute
  '/classes/$classId/quizzes/$quizId': typeof ClassesClassIdQuizzesQuizIdRoute
  '/classes/$classId/quizzes/generate': typeof ClassesClassIdQuizzesGenerateRoute
  '/classes/$classId/quizzes/new': typeof ClassesClassIdQuizzesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/dashboard'
    | '/focus'
    | '/journey'
    | '/library'
    | '/login'
    | '/progress'
    | '/register'
    | '/settings'
    | '/tasks'
    | '/wellness'
    | '/classes/$classId'
    | '/game/join'
    | '/quizzes/$quizId'
    | '/reports/$sessionId'
    | '/admin/'
    | '/classes/'
    | '/reports/'
    | '/admin/content/$quizId'
    | '/admin/content/generate'
    | '/admin/content/new'
    | '/game/host/$sessionId'
    | '/game/play/$sessionId'
    | '/admin/content/'
    | '/classes/$classId/'
    | '/classes/$classId/quizzes/$quizId'
    | '/classes/$classId/quizzes/generate'
    | '/classes/$classId/quizzes/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/dashboard'
    | '/focus'
    | '/journey'
    | '/library'
    | '/login'
    | '/progress'
    | '/register'
    | '/settings'
    | '/tasks'
    | '/wellness'
    | '/game/join'
    | '/quizzes/$quizId'
    | '/reports/$sessionId'
    | '/admin'
    | '/classes'
    | '/reports'
    | '/admin/content/$quizId'
    | '/admin/content/generate'
    | '/admin/content/new'
    | '/game/host/$sessionId'
    | '/game/play/$sessionId'
    | '/admin/content'
    | '/classes/$classId'
    | '/classes/$classId/quizzes/$quizId'
    | '/classes/$classId/quizzes/generate'
    | '/classes/$classId/quizzes/new'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/dashboard'
    | '/focus'
    | '/journey'
    | '/library'
    | '/login'
    | '/progress'
    | '/register'
    | '/settings'
    | '/tasks'
    | '/wellness'
    | '/classes/$classId'
    | '/game/join'
    | '/quizzes/$quizId'
    | '/reports/$sessionId'
    | '/admin/'
    | '/classes/'
    | '/reports/'
    | '/admin/content/$quizId'
    | '/admin/content/generate'
    | '/admin/content/new'
    | '/game/host/$sessionId'
    | '/game/play/$sessionId'
    | '/admin/content/'
    | '/classes/$classId/'
    | '/classes/$classId/quizzes/$quizId'
    | '/classes/$classId/quizzes/generate'
    | '/classes/$classId/quizzes/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  DashboardRoute: typeof DashboardRoute
  FocusRoute: typeof FocusRoute
  JourneyRoute: typeof JourneyRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  ProgressRoute: typeof ProgressRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  WellnessRoute: typeof WellnessRoute
  ClassesClassIdRoute: typeof ClassesClassIdRouteWithChildren
  GameJoinRoute: typeof GameJoinRoute
  QuizzesQuizIdRoute: typeof QuizzesQuizIdRoute
  ReportsSessionIdRoute: typeof ReportsSessionIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ClassesIndexRoute: typeof ClassesIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  AdminContentQuizIdRoute: typeof AdminContentQuizIdRoute
  AdminContentGenerateRoute: typeof AdminContentGenerateRoute
  AdminContentNewRoute: typeof AdminContentNewRoute
  GameHostSessionIdRoute: typeof GameHostSessionIdRoute
  GamePlaySessionIdRoute: typeof GamePlaySessionIdRoute
  AdminContentIndexRoute: typeof AdminContentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wellness': {
      id: '/wellness'
      path: '/wellness'
      fullPath: '/wellness'
      preLoaderRoute: typeof WellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/': {
      id: '/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof ClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$classId': {
      id: '/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/classes/$classId'
      preLoaderRoute: typeof ClassesClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/join': {
      id: '/game/join'
      path: '/game/join'
      fullPath: '/game/join'
      preLoaderRoute: typeof GameJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/$quizId': {
      id: '/quizzes/$quizId'
      path: '/quizzes/$quizId'
      fullPath: '/quizzes/$quizId'
      preLoaderRoute: typeof QuizzesQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$sessionId': {
      id: '/reports/$sessionId'
      path: '/reports/$sessionId'
      fullPath: '/reports/$sessionId'
      preLoaderRoute: typeof ReportsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/': {
      id: '/admin/content/'
      path: '/admin/content'
      fullPath: '/admin/content/'
      preLoaderRoute: typeof AdminContentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/$quizId': {
      id: '/admin/content/$quizId'
      path: '/admin/content/$quizId'
      fullPath: '/admin/content/$quizId'
      preLoaderRoute: typeof AdminContentQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/generate': {
      id: '/admin/content/generate'
      path: '/admin/content/generate'
      fullPath: '/admin/content/generate'
      preLoaderRoute: typeof AdminContentGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/new': {
      id: '/admin/content/new'
      path: '/admin/content/new'
      fullPath: '/admin/content/new'
      preLoaderRoute: typeof AdminContentNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$classId/': {
      id: '/classes/$classId/'
      path: '/'
      fullPath: '/classes/$classId/'
      preLoaderRoute: typeof ClassesClassIdIndexRouteImport
      parentRoute: typeof ClassesClassIdRoute
    }
    '/game/host/$sessionId': {
      id: '/game/host/$sessionId'
      path: '/game/host/$sessionId'
      fullPath: '/game/host/$sessionId'
      preLoaderRoute: typeof GameHostSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/play/$sessionId': {
      id: '/game/play/$sessionId'
      path: '/game/play/$sessionId'
      fullPath: '/game/play/$sessionId'
      preLoaderRoute: typeof GamePlaySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$classId/quizzes/$quizId': {
      id: '/classes/$classId/quizzes/$quizId'
      path: '/quizzes/$quizId'
      fullPath: '/classes/$classId/quizzes/$quizId'
      preLoaderRoute: typeof ClassesClassIdQuizzesQuizIdRouteImport
      parentRoute: typeof ClassesClassIdRoute
    }
    '/classes/$classId/quizzes/generate': {
      id: '/classes/$classId/quizzes/generate'
      path: '/quizzes/generate'
      fullPath: '/classes/$classId/quizzes/generate'
      preLoaderRoute: typeof ClassesClassIdQuizzesGenerateRouteImport
      parentRoute: typeof ClassesClassIdRoute
    }
    '/classes/$classId/quizzes/new': {
      id: '/classes/$classId/quizzes/new'
      path: '/quizzes/new'
      fullPath: '/classes/$classId/quizzes/new'
      preLoaderRoute: typeof ClassesClassIdQuizzesNewRouteImport
      parentRoute: typeof ClassesClassIdRoute
    }
  }
}

interface ClassesClassIdRouteChildren {
  ClassesClassIdIndexRoute: typeof ClassesClassIdIndexRoute
  ClassesClassIdQuizzesQuizIdRoute: typeof ClassesClassIdQuizzesQuizIdRoute
  ClassesClassIdQuizzesGenerateRoute: typeof ClassesClassIdQuizzesGenerateRoute
  ClassesClassIdQuizzesNewRoute: typeof ClassesClassIdQuizzesNewRoute
}

const ClassesClassIdRouteChildren: ClassesClassIdRouteChildren = {
  ClassesClassIdIndexRoute: ClassesClassIdIndexRoute,
  ClassesClassIdQuizzesQuizIdRoute: ClassesClassIdQuizzesQuizIdRoute,
  ClassesClassIdQuizzesGenerateRoute: ClassesClassIdQuizzesGenerateRoute,
  ClassesClassIdQuizzesNewRoute: ClassesClassIdQuizzesNewRoute,
}

const ClassesClassIdRouteWithChildren = ClassesClassIdRoute._addFileChildren(
  ClassesClassIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  DashboardRoute: DashboardRoute,
  FocusRoute: FocusRoute,
  JourneyRoute: JourneyRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  ProgressRoute: ProgressRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  WellnessRoute: WellnessRoute,
  ClassesClassIdRoute: ClassesClassIdRouteWithChildren,
  GameJoinRoute: GameJoinRoute,
  QuizzesQuizIdRoute: QuizzesQuizIdRoute,
  ReportsSessionIdRoute: ReportsSessionIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ClassesIndexRoute: ClassesIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  AdminContentQuizIdRoute: AdminContentQuizIdRoute,
  AdminContentGenerateRoute: AdminContentGenerateRoute,
  AdminContentNewRoute: AdminContentNewRoute,
  GameHostSessionIdRoute: GameHostSessionIdRoute,
  GamePlaySessionIdRoute: GamePlaySessionIdRoute,
  AdminContentIndexRoute: AdminContentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
